#!/bin/bash

sed -i '/add subzones below/a \
	\
zone "'"$1"'.wouter-baeyens.sb.uclllabs.be" {\
       type master; \
       file "/etc/bind/zones/'"$1"'.wouter-baeyens.sb.uclllabs.be.db"; \
       };' /etc/bind/named.conf.local

sed -i '/;delegated zones/a \
'"$1"'\tIN NS ns.wouter-baeyens.sb.uclllabs.be' /etc/bind/zones/wouter-baeyens.sb.uclllabs.be.db

#update serial safter adding subzone NS to main zone
sed -ri 's/(.*)([0-9]+)(.*)(; Serial)/echo "\1\$((\2+1))\3\4"/ge' "/etc/bind/zones/wouter-baeyens.sb.uclllabs.be.db"

echo '@	IN SOA ns.wouter-baeyens.sb.uclllabs.be. root.wouter-baeyens.sb.uclllabs.be. (
	1 	; Serial
	43200	; Refresh 
	3600	; Retry 
	129600	; Expire
	180 )	; Minimum TTL
; Nameservers
	IN NS ns.wouter-baeyens.sb.uclllabs.be. 
; additional records' > "/etc/bind/zones/$1.wouter-baeyens.sb.uclllabs.be.db"
